### ISSUE TITLE
Terraform crashes due to float conversion

### ISSUE THREAD

**Issue by meghana-rajashekar** [CiscoDevNet/terraform-provider-intersight#144]
**Describe the bug**
Terraform crashes when trying to create a resource with a float value key

**To Reproduce**
1. Resource for 'intersight_capability_equipment_slot_array'
```hcl
resource "intersight_capability_equipment_slot_array" "capability_equipment_slot_array1" {
  name   = "capability_equipment_slot_array1"
  pid    = "UCS-FI-6454"
  sku    = "CON-NCF4P-FI6454CH"
  height = 4.4
  width  = 43.9
}
```

2. Run `terraform apply` 
3. Output produced:
```bash
Stack trace from the terraform-provider-intersight_v1.0.17.exe plugin:

panic: interface conversion: interface {} is float64, not float32

goroutine 586 [running]:
github.com/CiscoDevNet/terraform-provider-intersight/intersight.resourceCapabilityEquipmentSlotArrayCreate({0x90bd768, 0xc00573bf80}, 0xc007a4f7b8, {0x7496860, 0xc007bd6230})
        github.com/CiscoDevNet/terraform-provider-intersight/intersight/resource_intersight_capability_equipment_slot_array.go:482 +0x1994
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004b8cc0, {0x90bd6f8, 0xc006015ec0}, 0x2, {0x7496860, 0xc007bd6230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:285 +0x1a3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004b8cc0, {0x90bd6f8, 0xc006015ec0}, 0xc0057492d0, 0xc0060486a0, {0x7496860, 0xc007bd6230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:396 +0x86f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003043a8, {0x90bd6f8, 0xc006015ec0}, 0xc002845400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000090d20, {0x90bd7a0, 0xc006034bd0}, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7b4bfc0, 0xc000090d20}, {0x90bd7a0, 0xc006034bd0}, 0xc00573b980, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a2540, {0x90d7b90, 0xc0014fe000}, 0xc00009b500, 0xc0040c22d0, 0xd8a6aa0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0003a2540, {0x90d7b90, 0xc0014fe000}, 0xc00009b500, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-intersight_v1.0.17.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
 

**Expected behavior**
Terraform should not crash but convert interface to float and set the value.

**Provider Version :** v1.0.17

**Comment by vvb** [comment]
fixed with 1.0.18
