### ISSUE TITLE
Terraform crashes due to nil to string conversion

### ISSUE THREAD

**Issue by meghana-rajashekar** [CiscoDevNet/terraform-provider-intersight#145]
**Describe the bug**
Terraform crashes when trying to create a resource with a list value [""]

**To Reproduce**
1. Create the following resource with docker_no_proxy = [""]
```hcl
resource "intersight_kubernetes_container_runtime_policy" "kubernetes_container_runtime_policy1" {
  description = "kubernetes container runtime policy"
  name        = "kubernetes_container_runtime_policy1"
  docker_http_proxy {
    hostname = "10.1.1.10"
    password = "ChangeMe"
    port     = 3001
    protocol = "http"
    username = "admin1"
  }
  docker_https_proxy {
    hostname = "10.1.1.10"
    password = "ChangeMe"
    port     = 3001
    protocol = "https"
    username = "admin1"
  }
  docker_no_proxy = [""]
  organization {
    object_type = "organization.Organization"
    moid        = var.organization
  }
}
```
2. Run `terraform apply` 
3. Output given:
```bash
Stack trace from the terraform-provider-intersight_v1.0.17.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 417 [running]:
github.com/CiscoDevNet/terraform-provider-intersight/intersight.resourceKubernetesContainerRuntimePolicyCreate({0x90bd768, 0xc007787020}, 0xc00aa2f7b8, {0x7496860, 0xc0082b6230})
        github.com/CiscoDevNet/terraform-provider-intersight/intersight/resource_intersight_kubernetes_container_runtime_policy.go:776 +0x1f25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0009ce3c0, {0x90bd6f8, 0xc0077aee80}, 0x2, {0x7496860, 0xc0082b6230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:285 +0x1a3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009ce3c0, {0x90bd6f8, 0xc0077aee80}, 0xc007848310, 0xc007854c60, {0x7496860, 0xc0082b6230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:396 +0x86f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000004d80, {0x90bd6f8, 0xc0077aee80}, 0xc0067c3f90)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000384d40, {0x90bd7a0, 0xc0077f7d70}, 0xc00601fd70)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7b4bfc0, 0xc000384d40}, {0x90bd7a0, 0xc0077f7d70}, 0xc0077869c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ac540, {0x90d7b90, 0xc00413e000}, 0xc006a43700, 0xc0040f42d0, 0xd8a6aa0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0003ac540, {0x90d7b90, 0xc00413e000}, 0xc006a43700, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-intersight_v1.0.17.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**
Terraform shouldn't crash when a nil value is passed inside the list

**Provider Version :** v1.0.17

**Comment by vvb** [comment]
fixed with 1.0.18
