### ISSUE TITLE
Terraform Crash for data "intersight_organization_organization" when org does not exist in Intersight

### ISSUE THREAD

**Issue by vungurea** [CiscoDevNet/terraform-provider-intersight#77]
I am getting a terraform crash when a data object of type intersight_organization_organization object does not exist. I know for sure that var.org_name has a value that does not exist into Intersight but the provider should handle this situation gracefully and not crash...

The data field is defined like this:

data "intersight_organization_organization" "intersight_organization" {
    name = var.org_name
}

VUNGUREA-M-J1HL:my-new-hxcluster vungurea$ terraform version
Terraform v0.14.7
+ provider registry.terraform.io/ciscodevnet/intersight v1.0.5

Your version of Terraform is out of date! The latest version
is 0.14.9. You can update by downloading from https://www.terraform.io/downloads.html
VUNGUREA-M-J1HL:my-new-hxcluster vungurea$
VUNGUREA-M-J1HL:my-new-hxcluster vungurea$ terraform plan

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: index out of range [0] with length 0
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5:
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: goroutine 54 [running]:
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/CiscoDevNet/terraform-provider-intersight/intersight.dataSourceOrganizationOrganizationRead(0x803b440, 0xc002b26840, 0xc002c12f80, 0x6a9b4c0, 0xc0000bd0e0, 0xc004ca8570, 0xc0038b9950, 0x100df58)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/CiscoDevNet/terraform-provider-intersight/intersight/data_source_intersight_organization_organization.go:206 +0x2c18
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc001e2d500, 0x803b3c0, 0xc002e98900, 0xc002c12f80, 0x6a9b4c0, 0xc0000bd0e0, 0x0, 0x0, 0x0)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:297 +0x1ea
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc001e2d500, 0x803b3c0, 0xc002e98900, 0xc000315600, 0x6a9b4c0, 0xc0000bd0e0, 0xc0000bd0e0, 0xc000315600, 0x0, 0x0)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:498 +0xfd
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000270540, 0x803b3c0, 0xc002e98900, 0xc0003153c0, 0xc002e98900, 0x6efea20, 0x709df00)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:1105 +0x4d4
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc002e4f380, 0x803b3c0, 0xc002e98900, 0xc0000bdb30, 0xc002e4f380, 0xc0044c6f00, 0xc0005b5ba0)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:247 +0xe5
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x709df00, 0xc002e4f380, 0x803b480, 0xc0044c6f00, 0xc002b26660, 0x0, 0x803b480, 0xc0044c6f00, 0xc002c943c0, 0xba)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002bafc0, 0x8043c00, 0xc000001980, 0xc000104e00, 0xc0028b7830, 0xb42f9f0, 0x0, 0x0, 0x0)
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-04-09T17:01:21.893+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: google.golang.org/grpc.(*Server).handleStream(0xc0002bafc0, 0x8043c00, 0xc000001980, 0xc000104e00, 0x0)
2021-04-09T17:01:21.894+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-04-09T17:01:21.894+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a1850, 0xc0002bafc0, 0x8043c00, 0xc000001980, 0xc000104e00)
2021-04-09T17:01:21.894+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-04-09T17:01:21.894+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-09T17:01:21.894+0200 [DEBUG] plugin.terraform-provider-intersight_v1.0.5: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021-04-09T17:01:21.900+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/09 17:01:21 [TRACE] vertex "module.hyperflex_profile.data.intersight_organization_organization.intersight_organization": visit complete
2021/04/09 17:01:21 [TRACE] vertex "module.hyperflex_profile.data.intersight_organization_organization.intersight_organization": dynamic subgraph encountered errors
2021/04/09 17:01:21 [TRACE] vertex "module.hyperflex_profile.data.intersight_organization_organization.intersight_organization": visit complete
2021/04/09 17:01:21 [TRACE] vertex "module.hyperflex_profile.data.intersight_organization_organization.intersight_organization (expand)": dynamic subgraph encountered errors
2021/04/09 17:01:21 [TRACE] vertex "module.hyperflex_profile.data.intersight_organization_organization.intersight_organization (expand)": visit complete
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_auto_support_policy.hx-auto-support-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_sys_config_policy.hx-sys-config-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_vcenter_config_policy.hx-vcenter-config-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_local_credential_policy.hx-local-credential-policy (expand)" errored, so skipping
2021-04-09T17:01:21.900+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/ciscodevnet/intersight/1.0.5/darwin_amd64/terraform-provider-intersight_v1.0.5 pid=9083 error="exit status 2"
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_software_version_policy.hx-software-version-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_cluster_storage_policy.hx-cluster-storage-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_node_config_policy.hx-node-config-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_cluster_network_policy.hx-cluster-network-policy (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile.intersight_hyperflex_cluster_profile.hxlab-cluster_profile (expand)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/ciscodevnet/intersight\"] (close)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "module.hyperflex_profile (close)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/04/09 17:01:21 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/09 17:01:21 [INFO] backend/local: plan operation completed
2021/04/09 17:01:21 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/04/09 17:01:21 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-04-09T17:01:21.900+0200 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
VUNGUREA-M-J1HL:my-new-hxcluster vungurea$

**Comment by code-lucidal58** [comment]
Fixed with 1.0.6 release
