### ISSUE TITLE
using data source intersight_kubernetes_cluster_profile leads to a panic

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-intersight#95]
**Describe the bug**
Very simple configuration.  Only data intersight_kubernetes_cluster_profile in configuration, which leads to a panic

**To Reproduce**
Configuration File:

```
terraform {
  required_version = ">=0.15.0"

  required_providers {
    intersight = {
      source  = "CiscoDevNet/intersight"
      version = ">=1.0.7"
    }
  }
}

provider "intersight" {
  apikey    = var.api_key
  secretkey = var.secret_key
  endpoint  = var.endpoint
}

data "intersight_kubernetes_cluster_profile" "iac-cl1" {
  name = "iac-cl1"
}
```

```
tyscott@tyscott-desktop:~/IKS_TEST2$ terraform plan=main.plan
╷
│ Error: Plugin did not respond
│ 
│   with data.intersight_kubernetes_cluster_profile.iac-cl1,
│   on main.tf line 18, in data "intersight_kubernetes_cluster_profile" "iac-cl1":
│   18: data "intersight_kubernetes_cluster_profile" "iac-cl1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-intersight_v1.0.9 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 26 [running]:
github.com/CiscoDevNet/terraform-provider-intersight/intersight.flattenMapKubernetesClusterCertificateConfiguration(0xc0037b15c0, 0x2a, 0xc0037b15f0, 0x2a, 0xc0033f64b0, 0xc0037b1560, 0x2a, 0xc0037b1590, 0x2a, 0xc0033b9540, ...)
        github.com/CiscoDevNet/terraform-provider-intersight/intersight/flatten_functions.go:11118 +0xb33
github.com/CiscoDevNet/terraform-provider-intersight/intersight.dataSourceKubernetesClusterProfileRead(0x79cb028, 0xc003208240, 0xc000052480, 0x632a500, 0xc003188230, 0xc004d31230, 0xc0047c3948, 0x40e0f8)
        github.com/CiscoDevNet/terraform-provider-intersight/intersight/data_source_intersight_kubernetes_cluster_profile.go:216 +0x19b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc001e09bc0, 0x79cafb8, 0xc000141b80, 0xc000052480, 0x632a500, 0xc003188230, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:297 +0x1ed
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc001e09bc0, 0x79cafb8, 0xc000141b80, 0xc00320a300, 0x632a500, 0xc003188230, 0xc003188230, 0xc00320a300, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:498 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000132060, 0x79cafb8, 0xc000141b80, 0xc00320a0c0, 0xc000141b80, 0x40b965, 0x67ba8a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc003972800, 0x79cb060, 0xc000141b80, 0xc0032020a0, 0xc003972800, 0xc0032001b0, 0xc0008e5ba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x696b980, 0xc003972800, 0x79cb060, 0xc0032001b0, 0xc003208060, 0x0, 0x79cb060, 0xc0032001b0, 0xc00320e1e0, 0xe3)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002bee00, 0x79d2b98, 0xc000103c80, 0xc0001f6100, 0xc002e03500, 0xb193650, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002bee00, 0x79d2b98, 0xc000103c80, 0xc0001f6100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000315fc0, 0xc0002bee00, 0x79d2b98, 0xc000103c80, 0xc0001f6100)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-intersight_v1.0.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

tyscott@tyscott-desktop:~/IKS_TEST2$
```

**Expected behavior**
Should be able to utilize data plugin

**Screenshots and Terraform configurations**

**Provider Version :** v1.0.x
Version 1.0.9

**Additional context**

**Comment by code-lucidal58** [comment]
Resolved in 1.0.10 release
